export const ADD_EDUCATION = "ADD_EDUCATION";
export const GET_EDUCATIONS = "GET_EDUCATIONS";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";

export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const GET_EXPERIENCES = "GET_EXPERIENCES";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";

export const ADD_INTEREST = "ADD_INTEREST";
export const UPDATE_INTEREST = "UPDATE_INTEREST";
export const GET_INTERESTS = "GET_INTERESTS";
export const DELETE_INTEREST = "DELETE_INTEREST";

export const ADD_LANGUAGE = "ADD_LANGUAGE";
export const GET_LANGUAGES = "GET_LANGUAGES";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_PROFILE = "GET_PROFILE";

export const ADD_PROJECT = "ADD_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const ADD_SKILL = "ADD_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const GET_SKILLS = "GET_SKILLS";
export const DELETE_SKILL = "DELETE_SKILL";

export const ADD_CV = "ADD_CV";
export const UPDATE_CV = "UPDATE_CV";
export const GET_CVS = "GET_CVS";