export const ADD_EDUCATION = "ADD_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";

export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";

export const ADD_INTEREST = "ADD_INTEREST";
export const UPDATE_INTEREST = "UPDATE_INTEREST";
export const GET_INTERESTS = "GET_INTERESTS";


export const ADD_LANGUAGE = "ADD_LANGUAGE";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";

export const ADD_SKILL = "ADD_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";

export const ADD_CV = "ADD_CV";
export const UPDATE_CV = "UPDATE_CV";
export const GET_CV = "GET_CV";