# Generated by Django 4.0.2 on 2022-02-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVE', 'Archive')], default='ACTIVE', max_length=20),
        ),
    ]
